### ISSUE TITLE
Missing download sources

### ISSUE THREAD

**Issue by pshem** [keepassxreboot/keepassxreboot.github.io#28]
The Linux download page [https://keepassxc.org/download/#linux](url) is missing:

- the official Flatpak from flathub: 
```
flatpak install --from https://flathub.org/repo/appstream/org.keepassxc.KeePassXC.flatpakref
```
Due to how support for flatpaks is implemented, it is also enough to link to the flatpakref: [https://flathub.org/repo/appstream/org.keepassxc.KeePassXC.flatpakref](url)
-  distribution SolusOS package: `sudo eopkg install keepassx ` [https://dev.solus-project.com/source/keepassx/](url). 
PS. Solus still uses the KeePassX name since they didn't want to keep an unmaintained package

The Mac dowloads page is missing:
- MacPorts - I have no idea if that version is official. `sudo port install keepassxc` [https://www.macports.org/ports.php?by=name&substr=keepassxc](url)

Since Open BSD is now mainstream [https://github.com/keepassxreboot/keepassxc/pull/1025](url), it should probably be included on the downloads page in it's own page.

The Windows download [https://keepassxc.org/download/#windows](url) page is missing the reference to the Portable Apps version [https://portableapps.com/apps/utilities/keepassxc-portable](url). This is likely because the package isn't official.

Should I just make a PR to fix these?

**Comment by TheZ3ro** [comment]
I don't really like SolusOS using `keepassx` package name instead of `keepassxc`. 
This is bad for users, they don't know what they are installing.

For the BSD family, we should make a new tab in the download page.

**Comment by pshem** [comment]
I'm writing a website update PR. Some things look plain horrible, such as trying to divide a 12 column layout to 5 parts(with OS names)

**Comment by kyrios123** [comment]
Originally `keepassx` was in the Solus repository, but a few years ago it was superseded by `keepassxc`. The package name wasn't changed to allow a smooth transition to the users (instead of deprecating a package and adding a new one which would have caused confusion to some users who would have wondered why their application was suddenly uninstalled because not everyone read blog posts, social media, etc.).

Unlike what you seem to think it doesn't cause confusion with the users. From the GUI the whole description including the package name comes from the [appdata](https://github.com/keepassxreboot/keepassxc/blob/develop/share/linux/org.keepassxc.KeePassXC.appdata.xml) so at no time a user will see `keepassx`. From the CLI, it is true the package name is keepassx, but the description clearly mention KeepassXC.

So do you honestly believe users confused by this? 
![image](https://user-images.githubusercontent.com/7815316/87447629-1a7bb700-c5fb-11ea-9593-34baeaca691c.png)

**Comment by phoerious** [comment]
There is no reason for Solus not to change the package name like literally every other distribution on the planet. I also have never heard of Solus and don't see why we would need to add it to our website if users will install KeePassXC via their package manager anyway. We cannot cater for every niche distribution and have enough packages listed already.
